[add]HTML_CSS課題の完成
yrdwsn/hc_practice pull request #2
Opened 2023-07-09 14:07 UTC by yrdwsn

## 課題のリンク

https://github.com/happiness-chain/practice/blob/main/005.1.1_html_css/002_%E3%82%A2%E3%82%A6%E3%83%88%E3%83%97%E3%83%83%E3%83%88%E8%AA%B2%E9%A1%8C.md

## やったこと

HTML_CSSコーディング模写課題を完成させました。レビューをお願いいたします。

2023-07-10 06:42 UTC, ihatov08 commented
github pagesのURLお願いします！

2023-07-10 06:44 UTC, ihatov08 requested changes
[Video_2023_07_10-1.webm](https://github.com/yrdwsn/hc_practice/assets/14024165/3045bf49-f68c-434c-aa54-53c59447f02f)

本家とだいぶ異なるので修正お願いします 🙇

2023-07-16 08:08 UTC, yrdwsn commented
ご指摘ありがとうございます。修正しましたのでご確認をお願いいたします。

Github PagesのURLは以下になります。
https://yrdwsn.github.io/hc_practice/HTML_CSS/index.html

2023-07-16 13:36 UTC, ihatov08 commented
リンクが青色になっているので修正お願いします！

2023-07-16 14:53 UTC, yrdwsn commented
修正依頼ありがとうございます。一部タグが青色になっていた点について修正いたしました。ご確認のほどよろしくお願いいたします。

https://yrdwsn.github.io/hc_practice/HTML_CSS/index

2023-07-17 13:21 UTC, ihatov08 approved these changes
確認しました、LGTMです！

2023-07-17 13:39 UTC, merged